[package]
name = "tavox-lch"
version = "0.1.0"
description = "TAVOX LCH - Launcher de Minecraft"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.30"

# Binario lo más pequeño y ligero posible
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
